### ISSUE TITLE
The token '&&' is not a valid statement separator in this version.

### ISSUE THREAD

**Issue by SaadKhamis** [saramorillon/terraform-graph#3]
PS L:\terraform> terraform plan -out=plan && terraform show -json plan > plan.tfgraph
At line:1 char:26
+ terraform plan -out=plan && terraform show -json plan > plan.tfgraph
+                          ~~
The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
 
PS L:\terraform> terraform -version
Terraform v1.5.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.61.0
+ provider registry.terraform.io/hashicorp/local v2.4.0   
PS L:\terraform>

**Comment by saramorillon** [comment]
Hello, which version of powershell are you using? I recommand using v7 of powershell, which allows using `&&` as statement separator.

**Comment by saramorillon** [comment]
This issue is being discussed [here](https://github.com/saramorillon/terraform-graph/issues/5). I'll close this and invite you to contribute to this other discussion.
