### ISSUE TITLE
[Bug] Objects with keys containing periods (`.`) are split

### ISSUE THREAD

**Issue by Makeshift** [saramorillon/terraform-graph#4]
Hey! This is a fantastic little tool, thank you for this.

Having played with it a bit, I noticed that if you are doing a `for_each` on an object of key-value pairs, if the key has a period in it, the tool renders that as a new level in the object, eg

![image](https://github.com/saramorillon/terraform-graph/assets/345013/685e3e2e-a7ce-4b5b-b592-2ca6d380e9a4)

Cheers :)

**Comment by saramorillon** [comment]
Hello, thank you for reporting this issue. The fix is available in v1.4.1 of Terraform Graph.
