### ISSUE TITLE
[Feature] Independent scrolling for resources and properties

### ISSUE THREAD

**Issue by mattcockrell** [saramorillon/terraform-graph#7]
Can the changed resources list and the changed properties list be allowed to scroll independently?  Placing them in separate frames would also allow the row heights in the properties list to vertically fit the row contents.  Also, the resource list could be adapted to better show the linked objects within a hierarchy level.

**Comment by saramorillon** [comment]
Independent scrolling is available in v1.4.2.

However, I did not understand your last point, could you please develop?

>  Also, the resource list could be adapted to better show the linked objects within a hierarchy level.

**Comment by saramorillon** [comment]
Without more information, I'm closing this issue.
