### ISSUE TITLE
plan graph crashed

### ISSUE THREAD

**Issue by Dharshannnn** [saramorillon/terraform-graph#8]
panic: AttributeTypes on non-object Type

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Type.AttributeTypes(...)
        /Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/object_type.go:187
github.com/zclconf/go-cty/cty/convert.unifyObjectTypesToMap(0x1400141c2a8, 0x2, 0x2, 0x140032d7b01, 0x0, 0x10554f4d8, 0x140063ddb00, 0x3, 0x3)
        /Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/convert/unify.go:368 +0x5e0
github.com/zclconf/go-cty/cty/convert.unifyTupleTypesToList(0x1400141c2a8, 0x2, 0x2, 0x1, 0x18, 0x105ea8108, 0x18, 0x140063ddae8, 0x14000100000)
        /Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/convert/unify.go:487 +0x2dc
github.com/zclconf/go-cty/cty/convert.unifyTupleTypes(0x1400141c2a8, 0x2, 0x2, 0x140063d0001, 0x1, 0x1, 0x1400141c088, 0x1025368f4, 0x14002a45fc0)
        /Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/convert/unify.go:418 +0x68c
github.com/zclconf/go-cty/cty/convert.unify(0x1400141c2a8, 0x2, 0x2, 0x140063dda01, 0x10449c3f0, 0x10554f4d8, 0x0, 0x0, 0x0)
        /Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/convert/unify.go:85 +0x5b4
github.com/zclconf/go-cty/cty/convert.UnifyUnsafe(...)
        /Users/distiller/go/pkg/mod/github.com/zclconf/go-cty@v1.10.0/cty/convert/public.go:82
github.com/hashicorp/hcl/v2/hclsyntax.(*ConditionalExpr).Value(0x140005c0690, 0x0, 0x1, 0x1, 0x2, 0x14002a45f00, 0x1, 0x2, 0x0)
        /Users/distiller/go/pkg/mod/github.com/hashicorp/hcl/v2@v2.10.1/hclsyntax/expression.go:609 +0x163c
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalExpression(0x10449b0e8, 0x140005c0690, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/distiller/project/project/internal/command/jsonconfig/expression.go:40 +0x58
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalExpressions(0x10449b0b0, 0x14000fa42c0, 0x140064c8240, 0x10)
        /Users/distiller/project/project/internal/command/jsonconfig/expression.go:115 +0xf4
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalModuleCall(0x140009795f0, 0x140002c5b80, 0x140014d7820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:315 +0x2e4
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalModuleCalls(0x14000cf9040, 0x140014d7820, 0x1400068fe68)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:281 +0xe4
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalModule(0x14000cf9040, 0x140014d7820, 0x14000c0eee0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:250 +0x428
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalModuleCall(0x14000cf9040, 0x140002c58c0, 0x140014d7820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:316 +0x320
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalModuleCalls(0x14000d80d00, 0x140014d7820, 0x14000c0f226)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:281 +0xe4
github.com/hashicorp/terraform/internal/command/jsonconfig.marshalModule(0x14000d80d00, 0x140014d7820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:250 +0x428
github.com/hashicorp/terraform/internal/command/jsonconfig.Marshal(0x14000d80d00, 0x140014d7820, 0x14007cc8000, 0x7e40c, 0x80000, 0x0, 0x0)
        /Users/distiller/project/project/internal/command/jsonconfig/config.go:125 +0x84
github.com/hashicorp/terraform/internal/command/jsonplan.Marshal(0x14000d80d00, 0x140007d46e0, 0x1400757b2f0, 0x140014d7820, 0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/distiller/project/project/internal/command/jsonplan/plan.go:159 +0x384
github.com/hashicorp/terraform/internal/command.(*ShowCommand).Run(0x140006fe380, 0x1400004c0f0, 0x1, 0x2, 0x140006581c0)
        /Users/distiller/project/project/internal/command/show.go:152 +0x6e8
github.com/mitchellh/cli.(*CLI).Run(0x140006c4140, 0x140006561b0, 0x1039d2d0b, 0x4)
        /Users/distiller/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x2c4
main.wrappedMain(0x0)
        /Users/distiller/project/project/main.go:384 +0xda8
main.realMain(0x0)
        /Users/distiller/project/project/main.go:115 +0x434
main.main()
        /Users/distiller/project/project/main.go:58 +0x20
[crash.036935853.log](https://github.com/saramorillon/terraform-graph/files/14343916/crash.036935853.log)

**Comment by saramorillon** [comment]
Without more information, I'm closing this issue.
