### ISSUE TITLE
Error loading webview: ... after update to vs code 1.8.2

### ISSUE THREAD

**Issue by robinpecha** [saramorillon/terraform-graph#9]
Hi, first of all, I want to thank you for this uniqe amazing tool. Im using it daily and there is nothing like this. 
After my todays update of vs code to latest 1.89.0 extension stop working. It generates plan.tfgraph but then when I try opening it, vs code complains:
`Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..`
![image](https://github.com/saramorillon/terraform-graph/assets/9316280/62af0b8d-7baa-4f11-9c50-6772890e963b)

Terraform v1.8.2
VS Code 1.89.0
Ubuntu 22.04.2 LTS

Please save our civilization of poor humans tortured by output of terraform plan : ) Thank you

**Comment by saramorillon** [comment]
Hello fellow terraform user,

Thank you for sharing your nice comment!

I'm afraid I can't reproduce this error on my computer. Did you try :
1. regenerating the plan?
2. opening the graph file as text? (right click > `Open with...` > `Text Editor`)
3. restarting vscode?
4. reinstalling the extension?

Please tell me if any of these works. Thank you!

**Comment by robinpecha** [comment]
It works again, after relloading whole environment. Problem was some not realoaded components during upgrade. Sorry for false alert and thank you for rescue, you brave hero .)
